# Site settings

title: Degrees of Delta
email: info@degreesofdelta.com
description: >- # this means to ignore newlines until "baseurl:"
  Small changes can lead to large differences in results.
baseurl: ""
url: "http://degreesofdelta.com"
domain: degreesofdelta.com
#twitter_username: jekyllrb
github_username:  degreesofdelta

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-feed
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
